# Generated by Django 4.1.3 on 2023-01-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipeingredient_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baserecipe',
            name='author',
            field=models.CharField(default=None, max_length=127, verbose_name='Автор'),
        ),
    ]
