# Generated by Django 4.1.3 on 2023-01-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_baserecipe_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipephoto',
            old_name='vk_link',
            new_name='vk_photo_link',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='is_allergen',
            field=models.BooleanField(default=False, verbose_name='Распространённый аллерген?'),
        ),
        migrations.AddField(
            model_name='suggestedrecipe',
            name='vk_photo_link',
            field=models.CharField(default=None, max_length=255, verbose_name='Ссылка на фото в ВК'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Стандартный ингредиент?'),
        ),
    ]
