# Generated by Django 4.1.3 on 2023-01-26 15:16

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, unique=True, verbose_name='Название')),
                ('alternative_names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=127), blank=True, null=True, size=None, verbose_name='Альтернативные названия')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='SubstitutionHint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(unique=True, verbose_name='Текст подсказки')),
                ('ingredient', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='substitution', to='recipes.ingredient', verbose_name='Ингредиент')),
            ],
            options={
                'verbose_name': 'Подсказка по замене ингредиента',
                'verbose_name_plural': 'Подсказки по замене ингредиентов',
            },
        ),
        migrations.CreateModel(
            name='StorageHint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(unique=True, verbose_name='Текст подсказки')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='storage_hints', to='hints.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Подсказка по сроку хранения продукта',
                'verbose_name_plural': 'Подсказки по сроку хранения продуктов',
            },
        ),
        migrations.CreateModel(
            name='BoilHint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(unique=True, verbose_name='Текст подсказки')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='boil_hints', to='hints.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Подсказка по времени варки продукта',
                'verbose_name_plural': 'Подсказки по времени варки продуктов',
            },
        ),
    ]
